"""empty message

Revision ID: dea44cd7bd68
Revises: 
Create Date: 2019-10-11 20:53:13.533496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea44cd7bd68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_num', sa.String(length=32), nullable=True),
    sa.Column('class_name', sa.String(length=32), nullable=True),
    sa.Column('entrance_time', sa.Date(), nullable=True),
    sa.Column('college', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_info')
    # ### end Alembic commands ###
